### ISSUE TITLE
unexpected errors with recent version

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-epsagon#36]
**Is your feature request related to a problem? Please describe.**
since the update to epsagon@1.57.2 the following errors occur in helix-pipeline:

```
"errorMessage": "RangeError: Resource length mismatch (possibly incomplete body)",
            "errorStack": "RangeError: Resource length mismatch (possibly incomplete body)\n    at throwLengthMismatch (/nodejsAction/XXMDGfmj/html.js:30251:11)\n    at StreamResponse.validateIntegrity (/nodejsAction/XXMDGfmj/html.js:30401:13)\n    at awaitBuffer.then.already_1.tap.buffer (/nodejsAction/XXMDGfmj/html.js:30315:52)\n    at /nodejsAction/XXMDGfmj/html.js:30550:15\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
            "headers": {},
            "statusCode": 502
```

**Describe the solution you'd like**
no errors.

**Comment by tripodsan** [comment]
https://github.com/epsagon/epsagon-node/issues/249

**Comment by tripodsan** [comment]
still a problem:
https://github.com/epsagon/epsagon-node/issues/256
